# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fd7c473e50c021fb52b265ef16804e94a3ad407b5e7fe72b82a9d1364ada3e0d97256b043945aebb92e531802531019fe3c4f74b72d89e0b02930a6b0812b7a

test:
  secret_key_base: d85c34083c247692b5403b824b9809b3bf80dbc800872d2f291ec7d0cc5bd2b1aa4607e7f647113057ac0b767e8c56fa39d1d9d3316c73c71c798f9c9bff8a30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
